/// <reference path="agency" />
/// <reference path="calendar_dates" />
/// <reference path="calendar" />
/// <reference path="common" />
/// <reference path="fare_attributes" />
/// <reference path="feed_info" />
/// <reference path="routes" />
/// <reference path="shapes" />
/// <reference path="stops" />
/* /// <reference path="trips" /> */
